#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan  5 13:12:39 2018

@author: leo
"""

DEFAULT_ANALYZERS_TYPE = {}

"""

   "Etablissement"
    "Structure de recherche"
    "UAI"
    "Nom"
    "Numéro UMR"
    "Titre"
    "Corps et Grades"
    "Phyto"
    "SIRET"
    "ID publication"
    "Nom d'essai clinique"
    "Entreprise"
    "Département"
    "Code INSEE"
    "Partenaire de recherche"
    "Spécialité médicale"
    "Type structuré"
    "TVA"
    "Entité Géo"
    "Publication"
    "Entité MESR"
    "Institution de recherche"
    "NIF"
    "Numéro National de Structure"
    "Date"
    "Intitulé GRID"
    "Académie"
    "Article"
    "Texte"
    "Institution"
    "ID organisation"
    "Code Postal"
    "Région"
    "Voie"
    "DOI"
    "NIR"
    "ID"
    "Nom de personne"
    "SIREN"
    "Collaborateur d'essai clinique"
    "Téléphone"
    "Commune"
    "Mois"
    "Entité biomédicale"
    "Pays"
    "URL"
    "Education Nationale"
    "ISSN"
    "Prénom"
    "Entité agro"
    "Adresse"
    "Etablissement d'Enseignement Supérieur"
    "Email"
    "ID personne"
    "Année": 
    "Etablissement des premier et second degrés": 

"""