FROM python:3.5 
RUN apt-get install autoconf automake curl gcc g++ libtool pkg-config
WORKDIR /merge_machine
COPY requirements_api.txt requirements_api.txt
RUN pip3 install -r requirements_api.txt
RUN ldconfig
COPY . /merge_machine
EXPOSE 80
WORKDIR /merge_machine/merge_machine
CMD ["python3", "api.py"]
